name: Deploy to Apps Script

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install clasp
        run: npm install -g @google/clasp
      
      - name: Create clasprc.json
        run: |
          echo "${{ secrets.CLASPRC_BASE64 }}" | base64 --decode > ~/.clasprc.json
      
      - name: Create clasp.json
        run: |
          echo "${{ secrets.CLASP_BASE64 }}" | base64 --decode > .clasp.json
      
      - name: Push to Apps Script
        run: clasp push -f
